### PR TITLE
Move concurrent index creation error

### LINKED ISSUE #441: OrioleDB crashes on REINDEX if there are INVALID indexes
Creating indexes concurrently is not supported and it raises an error:
```
=# create index concurrently on tab (id);
ERROR:  concurrent indexes are not supported.
```
It also leaves an INVALID index:
```
=# \d tab
                Table "public.tab"
 Column │  Type   │ Collation │ Nullable │ Default
────────┼─────────┼───────────┼──────────┼─────────
 id     │ integer │           │          │
Indexes:
    "tab_id_idx" btree (id)
    "tab_id_idx1" btree (id) INVALID
```
Trying to reindex the table afterwards crashes Postgres:
```
=# reindex table tab;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
```

Here is the back trace:
```
  * frame #0: 0x0000000105b2c860 orioledb.dylib`o_index_drop(tbl=0x000000012002ecd8, ix_num=65535) at indices.c:1879:31 [opt]
    frame #1: 0x0000000105b2c2c4 orioledb.dylib`o_define_index(heap=0x000000012002ecd8, index=0x00000001200306d8, indoid=<unavailable>, reindex=false, old_ix_num=65535, result=0x000000012f853358) at indices.c:447:4 [opt]
    frame #2: 0x0000000105b4b4d0 orioledb.dylib`orioledb_ambuild(heap=0x000000012002ecd8, index=0x00000001200306d8, indexInfo=0x000000012f852c38) at handler.c:208:3 [opt]
    frame #3: 0x0000000104c47300 postgres`index_build(heapRelation=0x000000012002ecd8, indexRelation=0x00000001200306d8, indexInfo=0x000000012f852c38, isreindex=true, parallel=<unavailable>) at index.c:3012:10 [opt]
    frame #4: 0x0000000104c494ec postgres`reindex_index(stmt=<unavailable>, indexId=32986, skip_constraint_checks=<unavailable>, persistence='p', params=0x000000016b2950e0) at index.c:3749:2 [opt]
    frame #5: 0x0000000104c49854 postgres`reindex_relation(stmt=0x000000012f80c190, relid=24789, flags=5, params=0x000000016b2950e0) at index.c:4000:3 [opt]
    frame #6: 0x0000000104cd3c5c postgres`ExecReindex [inlined] ReindexTable(stmt=0x000000012f80c190, params=0x000000016b2950d0, isTopLevel=true) at indexcmds.c:2948:12 [opt]
    frame #7: 0x0000000104cd3c24 postgres`ExecReindex(pstate=<unavailable>, stmt=<unavailable>, isTopLevel=<unavailable>) at indexcmds.c:2751:4 [opt]
    frame #8: 0x0000000104ef72dc postgres`ProcessUtilitySlow(pstate=0x000000012880ee38, pstmt=0x000000012f80c240, queryString="reindex table tab;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, queryEnv=0x0000000000000000, dest=<unavailable>, qc=0x000000016b295848) at utility.c:1567:5 [opt]
    frame #9: 0x0000000104ef6250 postgres`standard_ProcessUtility(pstmt=0x000000012f80c240, queryString="reindex table tab;", readOnlyTree=<unavailable>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, queryEnv=0x0000000000000000, dest=0x000000012f80c600, qc=0x000000016b295848) at utility.c:0 [opt]
    frame #10: 0x0000000105b276f0 orioledb.dylib`orioledb_utility_command(pstmt=0x000000012f80c240, queryString="reindex table tab;", readOnlyTree=<unavailable>, context=<unavailable>, params=0x0000000000000000, env=<unavailable>, dest=<unavailable>, qc=0x000000016b295848) at ddl.c:1230:4 [opt]
    frame #11: 0x0000000104ef5868 postgres`PortalRunUtility(portal=0x000000010f054f00, pstmt=0x000000012f80c240, isTopLevel=true, setHoldSnapshot=false, dest=0x000000012f80c600, qc=0x000000016b295848) at pquery.c:1158:2 [opt]
    frame #12: 0x0000000104ef4f70 postgres`PortalRunMulti(portal=0x000000010f054f00, isTopLevel=true, setHoldSnapshot=false, dest=0x000000012f80c600, altdest=0x000000012f80c600, qc=0x000000016b295848) at pquery.c:1315:5 [opt]
    frame #13: 0x0000000104ef4988 postgres`PortalRun(portal=0x000000010f054f00, count=9223372036854775807, isTopLevel=true, run_once=<unavailable>, dest=0x000000012f80c600, altdest=0x000000012f80c600, qc=0x000000016b295848) at pquery.c:791:5 [opt]
    frame #14: 0x0000000104ef3a34 postgres`exec_simple_query(query_string="reindex table tab;") at postgres.c:1278:10 [opt]
    frame #15: 0x0000000104ef1784 postgres`PostgresMain(dbname=<unavailable>, username=<unavailable>) at postgres.c:0 [opt]
    frame #16: 0x0000000104eed0b4 postgres`BackendMain(startup_data=<unavailable>, startup_data_len=<unavailable>) at backend_startup.c:105:2 [opt]
    frame #17: 0x0000000104e51098 postgres`postmaster_child_launch(child_type=B_BACKEND, startup_data="", startup_data_len=4, client_sock=0x000000016b295c40) at launch_backend.c:277:3 [opt]
    frame #18: 0x0000000104e55458 postgres`ServerLoop [inlined] BackendStartup(client_sock=0x000000016b295c40) at postmaster.c:3579:8 [opt]
    frame #19: 0x0000000104e5532c postgres`ServerLoop at postmaster.c:1659:6 [opt]
    frame #20: 0x0000000104e530dc postgres`PostmasterMain(argc=<unavailable>, argv=<unavailable>) at postmaster.c:1357:11 [opt]
    frame #21: 0x0000000104d780b8 postgres`main(argc=3, argv=0x0000600003e9d400) at main.c:197:3 [opt]
```

### PR DESCRIPTION
**Pull request by homper**
Fixes #441

### CODE REVIEW

File: src/catalog/ddl.c [hunk 1]
```diff
@@ -1218,6 +1218,36 @@ orioledb_utility_command(PlannedStmt *pstmt,
...
+				RangeVarGetRelidExtended(stmt->relation, lockmode,
+										 0,
+										 RangeVarCallbackOwnsRelation,
+										 NULL);
+			rel = table_open(relid, lockmode);
+
+			if (is_orioledb_rel(rel))
+			{
+				table_close(rel, lockmode);
+				elog(ERROR, "concurrent index creation not supported for orioledb tables yet");
```
Comment (za-arthur) [inline src/catalog/ddl.c]:
```suggestion
				elog(ERROR, "concurrent index creation is not supported for orioledb tables yet");
```
