### PR TITLE
Fix STORAGE MAIN oversized values causing index row size error (#578)

### LINKED ISSUE #578: Large values with STORAGE MAIN fail in OrioleDB ; “index row size … exceeds orioledb maximum 2688”
* Environment: PostgreSQL 17; OrioleDB public beta 12; hstore
   * branch= `main` ( 2025-sep-19 )  - b59af82a3d2446dac13f3e94df11a880a164ca31
   * tested in docker environments.
* USING orioledb  + column attrs hstore STORAGE MAIN + large insert
    * `ERROR:  index row size 9520 exceeds orioledb maximum 2688 for table "o_hs"`
* Repro:

```sql
-- Insert fails with orioledb storage;  heap is OK;
CREATE EXTENSION IF NOT EXISTS orioledb;
CREATE EXTENSION IF NOT EXISTS hstore;
DROP TABLE IF EXISTS o_hs;
CREATE TABLE o_hs (
  id    integer,
  attrs hstore
) 
--USING heap;
USING orioledb;
ALTER TABLE o_hs ALTER COLUMN attrs SET STORAGE MAIN;
INSERT INTO o_hs (id, attrs)
SELECT 1, h FROM (
  WITH s AS (
    SELECT 'k' || g::text AS k, repeat('x', 20) AS v
    FROM generate_series(1, 300) g
  )
  SELECT hstore(array_agg(k), array_agg(v)) AS h FROM s
) t;

```
* Works with: STORAGE EXTENDED , or USING heap ;

with orioledb - log:
```sql
postgres=# CREATE EXTENSION IF NOT EXISTS orioledb;
NOTICE:  extension "orioledb" already exists, skipping
CREATE EXTENSION
postgres=# CREATE EXTENSION IF NOT EXISTS hstore;
NOTICE:  extension "hstore" already exists, skipping
CREATE EXTENSION
postgres=# DROP TABLE IF EXISTS o_hs;
DROP TABLE
postgres=# CREATE TABLE o_hs (
postgres(#   id    integer,
postgres(#   attrs hstore
postgres(# ) 
postgres-# --USING heap;
postgres-# USING orioledb;
CREATE TABLE
postgres=# ALTER TABLE o_hs ALTER COLUMN attrs SET STORAGE MAIN;
ALTER TABLE
postgres=# INSERT INTO o_hs (id, attrs)
postgres-# SELECT 1, h FROM (
postgres(#   WITH s AS (
postgres(#     SELECT 'k' || g::text AS k, repeat('x', 20) AS v
postgres(#     FROM generate_series(1, 300) g
postgres(#   )
postgres(#   SELECT hstore(array_agg(k), array_agg(v)) AS h FROM s
postgres(# ) t;
ERROR:  index row size 9520 exceeds orioledb maximum 2688 for table "o_hs"
postgres=# 
postgres=# \d+ o_hs
                                          Table "public.o_hs"
 Column |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 id     | integer |           |          |         | plain   |             |              | 
 attrs  | hstore  |           |          |         | main    |             |              | 
Access method: orioledb
```

with heap - OK.
```sql
postgres=# CREATE EXTENSION IF NOT EXISTS orioledb;
NOTICE:  extension "orioledb" already exists, skipping
CREATE EXTENSION
postgres=# CREATE EXTENSION IF NOT EXISTS hstore;
NOTICE:  extension "hstore" already exists, skipping
CREATE EXTENSION
postgres=# DROP TABLE IF EXISTS o_hs;
DROP TABLE
postgres=# CREATE TABLE o_hs (
postgres(#   id    integer,
postgres(#   attrs hstore
postgres(# ) 
postgres-# USING heap;
CREATE TABLE
postgres=# -- USING orioledb;
postgres=# ALTER TABLE o_hs ALTER COLUMN attrs SET STORAGE MAIN;
ALTER TABLE
postgres=# INSERT INTO o_hs (id, attrs)
postgres-# SELECT 1, h FROM (
postgres(#   WITH s AS (
postgres(#     SELECT 'k' || g::text AS k, repeat('x', 20) AS v
postgres(#     FROM generate_series(1, 300) g
postgres(#   )
postgres(#   SELECT hstore(array_agg(k), array_agg(v)) AS h FROM s
postgres(# ) t;
INSERT 0 1
postgres=# \d+ o_hs
                                          Table "public.o_hs"
 Column |  Type   | Collation | Nullable | Default | Storage | Compression | Stats target | Description 
--------+---------+-----------+----------+---------+---------+-------------+--------------+-------------
 id     | integer |           |          |         | plain   |             |              | 
 attrs  | hstore  |           |          |         | main    |             |              | 
Access method: heap

postgres=# 
```

Notes:
- Originally observed with postgis geography regression test. 
- Tested with docker environments.

```
docker build --pull --network=host --progress=plain \
    --build-arg ALPINE_VERSION="3.21" \
    --build-arg BUILD_CC_COMPILER="clang" \
    --build-arg PG_MAJOR="17" \
    -f docker/Dockerfile \
    -t orioletest:17-clang-alpine3.21_hstore_main .
```

### PR DESCRIPTION
**Pull request by ImreSamu**
⚠️  Disclosure: This patch was developed with the assistance of **Claude Opus 4.5**.    **Feel free to modify this patch extensively or reject it entirely** if the approach doesn't align with OrioleDB's architecture / policy.
 
  
Fixes #578 (  This issue blocks PostGIS regression tests on OrioleDB. ) 
  
When inserting large values into columns with `STORAGE MAIN`, OrioleDB fails with:
`ERROR: index row size XXXX exceeds orioledb maximum 2688 for table "..."`

Standard PostgreSQL handles this by falling back to out-of-line TOAST storage when compression alone isn't sufficient. This patch adds similar behavior to OrioleDB.

### Changes

**src/tuple/slot.c**: Added a second pass in `tts_orioledb_toast()` that forces STORAGE MAIN attributes to out-of-line storage when the tuple remains oversized after compression attempts. Attributes are processed largest-first to minimize external storage usage.

**test/sql/toast_main.sql**: New regression test covering:
  - Basic STORAGE MAIN with large text values (3200-8000 bytes)
  - UPDATE/DELETE operations
  - Multiple columns with different STORAGE options (MAIN/EXTENDED/PLAIN)
  - bytea type with STORAGE MAIN
  - Index on STORAGE MAIN column

### Test plan

  - [ ] `make USE_PGXS=1 regresscheck` passes
  - [ ] New `toast_main` test passes
  - [ ] Reproducer from issue #578 now works

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -132,6 +132,7 @@ REGRESSCHECKS = btree_sys_check \
 				tablespace \
 				temp \
 				toast \
+				toast_main \
```
Comment (pashkinelfe) [inline Makefile]: I propose adding this test into the existing toast.sql

**Review by pashkinelfe — CHANGES_REQUESTED** [review]

File: src/tuple/slot.c [hunk 2]
```diff
@@ -1327,12 +1327,71 @@ tts_orioledb_toast(TupleTableSlot *slot, OTableDescr *descr)
...
+	}
+
+	/*
+	 * Reset any remaining COMPRESSION_TRIED flags to OFF. These are MAIN
+	 * attributes that were compressed or didn't need out-of-line storage.
+	 */
+	for (i = 0; i < descr->ntoastable; i++)
+	{
+		toast_attn = descr->toastable[i] - ctid_off;
+		if (oslot->to_toast[toast_attn] == ORIOLEDB_TO_TOAST_COMPRESSION_TRIED)
```
Comment (pashkinelfe) [inline src/tuple/slot.c:1392]: It looks that existing code in tts_orioledb_toast() before this patch leaves ORIOLEDB_TO_TOAST_COMPRESSION_TRIED without setting ORIOLEDB_TO_TOAST_OFF. Is setting ORIOLEDB_TO_TOAST_OFF needed here?

Comment (ImreSamu) [reply src/tuple/slot.c:1392]: Good catch; 
yes, resetting to `ORIOLEDB_TO_TOAST_OFF` is required.

To verify this myself, I temporarily removed the reset and ran the new toast regression test in an assert-enabled build,  and it failed with  
`TRAP: failed Assert("oslot->to_toast[i] != ORIOLEDB_TO_TOAST_COMPRESSION_TRIED")` in `src/tuple/slot.c` (line 1518)`

**Comment by ImreSamu** [comment]
@pashkinelfe : 

Ready to review (  // Co-Authored-By: Claude Opus 4.6  // ) 

- Testing required a truncation option in orioledb_tbl_structure() output to keep large-value TOAST checks readable and stable;  https://github.com/orioledb/orioledb/pull/689/changes/77a7df1134fcafcb8868fcbf68a4c6c2712e20a7

- And I fully reworked the related TOAST test coverage, ( https://github.com/orioledb/orioledb/pull/689/changes/092e6612fc2f7cc69af830ffd8941aba5cbb06a5 ) 

- While leaving the core patch logic essentially unchanged.
https://github.com/orioledb/orioledb/pull/689/changes/22bec5361497f434d09251718df8862fc1a7d565     



// the [original obsolete commit backup](https://github.com/ImreSamu/orioledb/tree/backup_fix578_large_values_v3) //
